CREATE TABLE [dbo].[ProcedureToCreateExecutionMapping]
(
	[ProcedureName]		SYSNAME NOT NULL 
		CONSTRAINT PK_ProcedureToCreateExecutionMapping
			PRIMARY KEY CLUSTERED
,	[FOLDER_NAME]		NVARCHAR(128) NOT NULL
,	[PROJECT_NAME]		NVARCHAR(128) NOT NULL
,	[PACKAGE_NAME]		NVARCHAR(128) NOT NULL
,	[REFERENCE_ID]		BIGINT NOT NULL
)
